export type Product = {
  id: number;
  slug: string;
  sku?: string;
  name: string;
  bn: string;
  price: number;
  oldPrice: number;
  stock: number;
  rating: number;
  reviews: number;
  category: string;
  image: string;
  image2?: string;
  video?: string;
  tag?: string;
  description?: string;
  nutrition?: string;
  storageInstructions?: string;
};
